olympiad/api/urls.py
from django.urls import path
from .views import login_view
app_name = 'api'


urlpatterns = [
    path('api/login/', login_view, name='api-login'),
]

olympiad/chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('groups/create/', create_group, name='create_group'),
    path('groups/<int:group_id>/', group_detail, name='group_detail'),
    path('chats/', chat_list_view, name='chat_list'),
    path('start_chat/<str:username>/', start_chat, name='start_chat'),
    path('<str:username>/', chat_view, name='chat'),
    path('delete_message/<int:message_id>/', delete_message, name='delete_message'),
    path('update_message/<int:message_id>/', update_message, name='update_message'),
]

olympiad/olympiad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import StartPage
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('silk/', include('silk.urls', namespace='silk')),
    # Пока нет главной страницы, перенаправление на страницу входа
    path('', StartPage.as_view(), name='start_page'),
    # Главное приложение
    path('main/', include('main.urls', namespace='main')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('register/', include('register.urls', namespace='register')),
    path('result/', include('result.urls', namespace='result')),
    path('school/', include('school.urls', namespace='school')),
    path('classroom/', include('classroom.urls', namespace='classroom')),
    path('calendar/', include('calendar_olimp.urls', namespace='calendar')),
    # Приложения авторизации
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('chat/', include('chat.urls')),
]

# Обработка медиафайлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Обработка ошибки 404
handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

olympiad/chat/models.py
# chat/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings

User = get_user_model()


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_messages', on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    school = models.ForeignKey('school.School', on_delete=models.CASCADE, related_name='school_chat')
    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return f"{self.sender.username} to {self.recipient.username} at {self.timestamp}: {self.content}"

olympiad/chat/forms.py
from django import forms
from users.models import *
from .models import *


class MessageForm(forms.ModelForm):
    class Meta:
        # model = Message
        fields = ['recipient', 'content']

    recipient = forms.ModelChoiceField(queryset=User.objects.all(), label="Recipient")

olympiad/chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import *
from django.db.models import Q, Max
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from friendship.models import Friend
from .forms import *

User = get_user_model()


@login_required
def chat_view(request, username):
    other_user = get_object_or_404(User, username=username)
    messages = Message.objects.filter(
        (Q(sender=request.user) & Q(recipient=other_user)) |
        (Q(sender=other_user) & Q(recipient=request.user))
    ).order_by('timestamp')

    return render(request, 'chat/chat.html', {
        'other_user': other_user,
        'messages': messages
    })


@login_required
@require_POST
def delete_message(request, message_id):
    message = get_object_or_404(Message, id=message_id, sender=request.user)
    message.delete()
    return JsonResponse({'status': 'ok'})


@login_required
@require_POST
def update_message(request, message_id):
    message = get_object_or_404(Message, id=message_id, sender=request.user)
    new_content = request.POST.get('content')
    if new_content:
        message.content = new_content
        message.save()
    return JsonResponse({'status': 'ok', 'content': message.content})


@login_required
def chat_list_view(request):
    current_user = request.user
    friends = Friend.objects.friends(current_user)

    last_messages = (
        Message.objects
        .filter(
            (Q(sender=current_user) & Q(recipient__in=friends)) |
            (Q(recipient=current_user) & Q(sender__in=friends))
        )
        .annotate(last_message_id=Max('id'))
        .values('last_message_id')
    )

    last_message_ids = [item['last_message_id'] for item in last_messages]
    last_messages = Message.objects.filter(id__in=last_message_ids)

    friends_with_last_messages = [
        {'friend': friend,
         'last_message': next((msg for msg in last_messages if msg.sender == friend or msg.recipient == friend), None)}
        for friend in friends
    ]

    return render(request, 'chat/chat_list.html', {
        'friends_with_last_messages': friends_with_last_messages
    })


@login_required
def start_chat(request, username):
    other_user = get_object_or_404(User, username=username)
    return redirect('chat:chat', username=other_user.username)


@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save()
            return redirect('chat:group_detail', group_id=group.id)
    else:
        form = GroupForm()
    return render(request, 'chat/create_group.html', {'form': form})


@login_required
def group_detail(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    messages = GroupMessage.objects.filter(group=group).order_by('timestamp')
    return render(request, 'chat/group_detail.html', {'group': group, 'messages': messages})

olympiad/chat/templates/chat/chat.html
{% extends 'base_olimp.html' %}
{% load static %}
{% block content %}
    <h2 class="text-2xl font-bold mb-4">Чат с {{ other_user.username }}</h2>
    <div id="chat-log-container" class="overflow-y-scroll h-96 bg-white p-4 rounded shadow">
        <ul id="chat-log" class="space-y-4">
            {% for message in messages %}
                <li id="message-{{ message.id }}"
                    class="flex items-start space-x-4 {% if message.sender == request.user %}justify-end{% else %}justify-start{% endif %}">
                    <div class="max-w-xs bg-gray-200 p-2 rounded shadow-md">
                        <div class="font-semibold">{{ message.sender.username }}</div>
                        <div>{{ message.content }}</div>
                        <small class="text-gray-500">{{ message.timestamp }}</small>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="mt-4 flex">
        <input id="chat-message-input" type="text" class="flex-1 border border-gray-300 p-2 rounded-l-lg focus:outline-none" placeholder="Введите сообщение...">
        <button id="chat-message-submit" class="bg-blue-500 text-white px-4 py-2 rounded-r-lg hover:bg-blue-600">Отправить</button>
    </div>

    <div id="context-menu" class="hidden fixed bg-white border border-gray-300 rounded shadow-lg z-50">
        <ul class="py-1">
            <li id="reply" class="px-4 py-2 hover:bg-gray-200 cursor-pointer">Ответить</li>
            <li id="edit" class="px-4 py-2 hover:bg-gray-200 cursor-pointer">Изменить</li>
            <li id="delete" class="px-4 py-2 hover:bg-gray-200 cursor-pointer">Удалить</li>
        </ul>
    </div>

    <script>
        const roomName = "{{ other_user.username }}";
        const chatSocket = new WebSocket(
            (window.location.protocol === 'https:' ? 'wss://' : 'ws://') + window.location.host + '/ws/chat/' + roomName + '/'
        );

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            const chatLog = document.getElementById('chat-log');
            const messageElement = document.createElement('li');
            messageElement.id = `message-${data.id}`;
            messageElement.className = `flex items-start space-x-4 ${data.sender === "{{ request.user.username }}" ? 'justify-end' : 'justify-start'}`;

            const avatarUrl = data.avatar ? data.avatar : '{% static "homepage/img/default-ava.png" %}';

            messageElement.innerHTML = `
                <img src="${avatarUrl}" alt="${data.sender}" class="w-12 h-12 rounded-full">
                <div class="max-w-xs bg-gray-200 p-2 rounded shadow-md">
                    <div class="font-semibold">${data.sender}</div>
                    <div>${data.message}</div>
                    <small class="text-gray-500">${new Date(data.timestamp).toLocaleString()}</small>
                </div>
            `;

            chatLog.appendChild(messageElement);
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.getElementById('chat-message-input').focus();
        document.getElementById('chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // Enter key
                document.getElementById('chat-message-submit').click();
            }
        };

        document.getElementById('chat-message-submit').onclick = function (e) {
            if (chatSocket.readyState === WebSocket.OPEN) {
                const messageInputDom = document.getElementById('chat-message-input');
                const message = messageInputDom.value;
                chatSocket.send(JSON.stringify({
                    'message': message
                }));
                messageInputDom.value = '';
            } else {
                console.error('WebSocket is not open.');
            }
        };

        function deleteMessage(messageId, url) {
            fetch(url, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            }).then(response => {
                if (response.ok) {
                    document.getElementById(`message-${messageId}`).remove();
                }
            });
        }

        function enableEditMessage(messageId) {
            const messageContentElement = document.querySelector(`#message-${messageId} .message-content`);
            const newContent = prompt("Введите новое сообщение:", messageContentElement.innerText);
            if (newContent) {
                fetch(`{% url 'chat:update_message' 0 %}`.replace('0', messageId), {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: `content=${encodeURIComponent(newContent)}`
                }).then(response => response.json())
                    .then(data => {
                        if (data.status === 'ok') {
                            messageContentElement.innerText = data.content;
                        }
                    });
            }
        }

        function replyMessage(messageId) {
            const messageContentElement = document.querySelector(`#message-${messageId} .message-content`);
            const messageInputDom = document.getElementById('chat-message-input');
            messageInputDom.value = `@${messageContentElement.previousElementSibling.innerText.trim()}: ${messageContentElement.innerText}\n` + messageInputDom.value;
            messageInputDom.focus();
        }

        // Context menu
        const contextMenu = document.getElementById('context-menu');
        let contextMessageId = null;

        document.addEventListener('contextmenu', function (event) {
            const messageElement = event.target.closest('.chat-message');
            if (messageElement) {
                event.preventDefault();
                contextMessageId = messageElement.id.split('-')[1];
                contextMenu.style.top = `${event.pageY}px`;
                contextMenu.style.left = `${event.pageX}px`;
                contextMenu.classList.add('active');
            }
        });

        document.addEventListener('click', function (event) {
            if (!event.target.closest('#context-menu')) {
                contextMenu.classList.remove('active');
            }
        });

        document.getElementById('delete').onclick = function () {
            deleteMessage(contextMessageId, `{% url 'chat:delete_message' 0 %}`.replace('0', contextMessageId));
        };

        document.getElementById('edit').onclick = function () {
            enableEditMessage(contextMessageId);
        };

        document.getElementById('reply').onclick = function () {
            replyMessage(contextMessageId);
        };
    </script>
{% endblock %}

olympiad/chat/templates/chat/chat_list.html
{% extends 'base_olimp.html' %}
{% load static %}
{% block title %}Сообщения{% endblock %}

{% block content %}
    <h2 class="text-2xl font-bold mb-4">Сообщения</h2>
    <div class="mb-6">
        <a href="{% url 'chat:create_group' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Создать
            группу</a>
    </div>
    <ul class="space-y-4">
        {% for item in friends_with_last_messages %}
            <li class="flex items-center space-x-4">
                <img src="
                        {% if item.friend.image %}{{ item.friend.image.url }}{% else %}{% static 'homepage/img/default-ava.png' %}{% endif %}"
                     alt="{{ item.friend.get_full_name }}" class="w-12 h-12 rounded-full">
                <div>
                    <strong>{{ item.friend.get_full_name }}</strong><br>
                    {% if item.last_message %}
                        <small class="text-gray-600">{{ item.last_message.timestamp }}:
                            {{ item.last_message.content|truncatechars:30 }}</small><br>
                    {% else %}
                        <small class="text-gray-600">Нет сообщений</small><br>
                    {% endif %}
                    <form action="{% url 'chat:start_chat' item.friend.username %}" method="post" class="inline">
                        {% csrf_token %}
                        <button type="submit" class="bg-green-500 text-white px-2 py-1 rounded hover:bg-green-600">
                            Начать чат
                        </button>
                    </form>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

olympiad/chat/templates/chat/create_group.html
<!-- templates/chat/create_group.html -->

{% extends 'base_olimp.html' %}

{% block content %}
<h2>Создать группу</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
</form>
{% endblock %}

olympiad/chat/templates/chat/group_detail.html
<!-- templates/chat/group_detail.html -->

{% extends 'base_olimp.html' %}
{% load static %}
{% block content %}
<h2>Группа: {{ group.name }}</h2>
<div id="chat-log-container" class="chat-log-container">
    <ul id="chat-log" class="chat-log">
        {% for message in messages %}
            <li id="message-{{ message.id }}" class="chat-message {% if message.sender == request.user %}sent{% else %}received{% endif %}">
                {% if message.sender.image %}
                    <img src="{{ message.sender.image.url }}" alt="{{ message.sender.username }}" class="chat-avatar">
                {% else %}
                    <img src="{% static 'homepage/img/default-ava.png' %}" alt="{{ message.sender.username }}" class="chat-avatar">
                {% endif %}
                <div class="message-content-container">
                    <strong>{{ message.sender.username }}:</strong>
                    {% if message.reply_to %}
                        <div class="reply-message">
                            <strong>{{ message.reply_to.sender.username }}</strong>: {{ message.reply_to.content|truncatechars:50 }}
                        </div>
                    {% endif %}
                    <span class="message-content">{{ message.content }}</span>
                    <small>({{ message.timestamp }})</small>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
<input id="chat-message-input" type="text" class="chat-input">
<button id="chat-message-submit" class="chat-submit">Отправить</button>

<div id="context-menu" class="context-menu">
    <ul>
        <li id="reply">Ответить</li>
        <li id="edit">Изменить</li>
        <li id="delete">Удалить</li>
    </ul>
</div>

<script>
    const groupId = "{{ group.id }}";
    const chatSocket = new WebSocket(
        (window.location.protocol === 'https:' ? 'wss://' : 'ws://') + window.location.host + '/ws/chat/group/' + groupId + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const chatLog = document.getElementById('chat-log');
        const messageElement = document.createElement('li');
        messageElement.id = `message-${data.id}`;
        messageElement.className = `chat-message ${data.sender === "{{ request.user.username }}" ? 'sent' : 'received'}`;

        const avatarUrl = data.avatar ? data.avatar : '{% static "homepage/img/default-ava.png" %}';
        const updateUrl = '{% url "chat:update_message" 0 %}'.replace('0', data.id);
        const deleteUrl = '{% url "chat:delete_message" 0 %}'.replace('0', data.id);

        let replyMessageHtml = '';
        if (data.reply_to) {
            replyMessageHtml = `
                <div class="reply-message">
                    <strong>${data.reply_to.sender}</strong>: ${data.reply_to.content}
                </div>
            `;
        }

        messageElement.innerHTML = `
            <img src="${avatarUrl}" alt="${data.sender}" class="chat-avatar">
            <div class="message-content-container">
                <strong>${data.sender}:</strong>
                ${replyMessageHtml}
                <span class="message-content">${data.message}</span>
                <small>(${new Date().toLocaleString()})</small>
            </div>
        `;

        chatLog.appendChild(messageElement);
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.getElementById('chat-message-input').focus();
    document.getElementById('chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {
            document.getElementById('chat-message-submit').click();
        }
    };

    document.getElementById('chat-message-submit').onclick = function(e) {
        if (chatSocket.readyState === WebSocket.OPEN) {
            const messageInputDom = document.getElementById('chat-message-input');
            const message = messageInputDom.value;
            const replyToMessageId = messageInputDom.getAttribute('data-reply-to');

            chatSocket.send(JSON.stringify({
                'message': message,
                'reply_to': replyToMessageId
            }));

            messageInputDom.value = '';
            messageInputDom.removeAttribute('data-reply-to');
        } else {
            console.error('WebSocket is not open.');
        }
    };

    function deleteMessage(messageId, url) {
        fetch(url, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        }).then(response => {
            if (response.ok) {
                document.getElementById(`message-${messageId}`).remove();
            }
        });
    }

    function enableEditMessage(messageId) {
        const messageContentElement = document.querySelector(`#message-${messageId} .message-content`);
        const newContent = prompt("Введите новое сообщение:", messageContentElement.innerText);
        if (newContent) {
            fetch(`{% url 'chat:update_message' 0 %}`.replace('0', messageId), {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: `content=${encodeURIComponent(newContent)}`
            }).then(response => response.json())
              .then(data => {
                if (data.status === 'ok') {
                    messageContentElement.innerText = data.content;
                }
            });
        }
    }

    function replyMessage(messageId) {
        const messageInputDom = document.getElementById('chat-message-input');
        messageInputDom.setAttribute('data-reply-to', messageId);
        messageInputDom.focus();
    }

    // Context menu
    const contextMenu = document.getElementById('context-menu');
    let contextMessageId = null;

    document.addEventListener('contextmenu', function(event) {
        const messageElement = event.target.closest('.chat-message');
        if (messageElement) {
            event.preventDefault();
            contextMessageId = messageElement.id.split('-')[1];
            contextMenu.style.top = `${event.pageY}px`;
            contextMenu.style.left = `${event.pageX}px`;
            contextMenu.classList.add('active');
        }
    });

    document.addEventListener('click', function(event) {
        if (!event.target.closest('#context-menu')) {
            contextMenu.classList.remove('active');
        }
    });

    document.getElementById('delete').onclick = function() {
        deleteMessage(contextMessageId, `{% url 'chat:delete_message' 0 %}`.replace('0', contextMessageId));
    };

    document.getElementById('edit').onclick = function() {
        enableEditMessage(contextMessageId);
    };

    document.getElementById('reply').onclick = function() {
        replyMessage(contextMessageId);
    };
</script>
{% endblock %}