olympiad/api/urls.py
from django.urls import path
from .views import login_view
app_name = 'api'


urlpatterns = [
    path('api/login/', login_view, name='api-login'),
]

olympiad/classroom/urls.py
from django.urls import path
from .views import (
    ChildrenListTeacher, TeacherClassroomGuide, ClassroomListView,
    ChildExpelAdmin, ChildReinstateAdmin, ChildClassroomListAdmin,
    ClassroomCreateView, ClassroomUpdateView, ClassroomDeleteView,
    PromoteAllClassroomsView
)

app_name = 'classroom'

urlpatterns = [
    path('teacher/list/<int:Classroom_id>/', ChildrenListTeacher.as_view(), name='children_list_teacher'),
    path('teacher/', TeacherClassroomGuide.as_view(), name='teacher_classroom_guide'),
    path('classroom/list/', ClassroomListView.as_view(), name='list_classroom'),
    path('child-expel/<int:User_id>/', ChildExpelAdmin.as_view(), name='child_expel_admin'),
    path('child-reinstate/<int:User_id>/', ChildReinstateAdmin.as_view(), name='child_reinstate_admin'),
    path('student/applications/admin/<int:Classroom_id>/', ChildClassroomListAdmin.as_view(), name='student_applications_admin'),
    path('new/', ClassroomCreateView.as_view(), name='classroom_create'),
    path('edit/<int:pk>/', ClassroomUpdateView.as_view(), name='classroom_update'),
    path('delete/<int:pk>/', ClassroomDeleteView.as_view(), name='classroom_delete'),
    path('promote_all/', PromoteAllClassroomsView.as_view(), name='promote_all_classrooms'),
]

olympiad/olympiad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import StartPage
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('silk/', include('silk.urls', namespace='silk')),
    # Пока нет главной страницы, перенаправление на страницу входа
    path('', StartPage.as_view(), name='start_page'),
    # Главное приложение
    path('main/', include('main.urls', namespace='main')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('register/', include('register.urls', namespace='register')),
    path('result/', include('result.urls', namespace='result')),
    path('school/', include('school.urls', namespace='school')),
    path('classroom/', include('classroom.urls', namespace='classroom')),
    path('calendar/', include('calendar_olimp.urls', namespace='calendar')),
    # Приложения авторизации
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('chat/', include('chat.urls')),
]

# Обработка медиафайлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Обработка ошибки 404
handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

olympiad/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    AuthLogin,
    logout,
    PasswordChange,
    CreateAdmin,
    CreateChild,
    CreateTeacher,
    TeacherListView,
    AdminListView,
    EditTeacherView,
    EditAdminView,
    DeleteUserView
)
from friends.views import ProfileView
from .forms import CustomPasswordResetForm

app_name = 'users'

urlpatterns = [
    # URL для страницы входа
    path('login/', AuthLogin.as_view(), name='login'),

    # URL для профиля пользователя по его ID
    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),

    # URL для выхода из системы
    path('logout/', logout, name='logout'),

    # URL для изменения пароля
    path('password_change/', PasswordChange.as_view(), name='password_change'),

    # URL для создания администратора
    path('create/admin/', CreateAdmin.as_view(), name='CreateAdmin'),

    # URL для создания ученика
    path('create/child/', CreateChild.as_view(), name='CreateChild'),

    # URL для создания учителя
    path('create/teacher/', CreateTeacher.as_view(), name='CreateTeacher'),

    # URL для списка учителей
    path('teachers/', TeacherListView.as_view(), name='teacher_list'),

    # URL для списка администраторов
    path('admins/', AdminListView.as_view(), name='admin_list'),

    # URL для редактирования информации об учителе
    path('teachers/edit/<int:pk>/', EditTeacherView.as_view(), name='edit_teacher'),

    # URL для редактирования информации об администраторе
    path('admins/edit/<int:pk>/', EditAdminView.as_view(), name='edit_admin'),

    # URL для удаления пользователя
    path('users/delete/<int:pk>/', DeleteUserView.as_view(), name='delete_user'),

    # URL для сброса пароля
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='auth/password_reset.html',
        success_url=reverse_lazy('users:password_reset_done'),
        form_class=CustomPasswordResetForm,
        email_template_name='auth/password_reset_email.html',
    ), name='password_reset'),

    # URL для подтверждения сброса пароля
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html',
         ),
         name='password_reset_done'),

    # URL для подтверждения сброса пароля по ссылке
    path('password_reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'),

    # URL для завершения сброса пароля
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='auth/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # URL для обновления Telegram ID (закомментировано, если потребуется в будущем)
    # path('update_telegram_id/', update_telegram_id, name='update_telegram_id'),
]

olympiad/classroom/models.py
from django.db import models
from datetime import datetime


class Classroom(models.Model):
    """Модель для представления класса в школе"""

    number = models.IntegerField('Цифра', blank=True, null=True)
    letter = models.CharField('Буква', max_length=1, blank=True, null=True)
    teacher = models.ForeignKey(
        'users.User', blank=True, null=True, on_delete=models.CASCADE, related_name='teacher', verbose_name='Учитель'
    )
    child = models.ManyToManyField(
        'users.User', blank=True, related_name='child', verbose_name='Ученики'
    )
    is_graduated = models.BooleanField('Выпустился', default=False)
    graduation_year = models.IntegerField('Год выпуска', blank=True, null=True)
    school = models.ForeignKey(
        'school.School', on_delete=models.CASCADE, verbose_name='Школа', related_name='classrooms'
    )

    def __str__(self):
        return f'{self.number} {self.letter} - {self.teacher}'

    def promote(self):
        """Метод для продвижения класса на следующий уровень или отметки как выпустившегося"""
        if self.number is not None and self.number < 11:
            self.number += 1
        else:
            self.is_graduated = True
            self.graduation_year = datetime.now().year
        self.save()

olympiad/classroom/forms.py
from django import forms
from classroom.models import *
from users.models import User


class ClassroomForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ClassroomForm, self).__init__(*args, **kwargs)
        self.fields['teacher'].queryset = User.get_teachers()
        self.fields['child'].queryset = User.get_children()

olympiad/classroom/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DeleteView, UpdateView, CreateView

from users.models import User
from users.mixins import AdminRequiredMixin
from classroom.models import Classroom
from .forms import ClassroomForm
from django.contrib import messages


class ChildrenListTeacher(LoginRequiredMixin, View):
    """Отображение списка детей для учителя в конкретном классе"""

    def get(self, request, Classroom_id):
        if request.user.is_teacher:
            classroom = get_object_or_404(Classroom, id=Classroom_id, school=request.user.school)
            classroom_children = User.objects.filter(classroom_id=Classroom_id, school=request.user.school)
            context = {
                'classroom': classroom,
                'children': classroom_children
            }
            return render(request, 'children_list_teacher/children_list_teacher.html', context)
        return HttpResponseForbidden()


class TeacherClassroomGuide(LoginRequiredMixin, View):
    """Отображение классов, закрепленных за учителем"""

    def get(self, request, *args, **kwargs):
        if request.user.is_teacher:
            classrooms = Classroom.objects.filter(teacher=request.user, school=request.user.school)
            context = {
                'classrooms': classrooms
            }
            return render(request, 'list_classroom_teacher/list_classroom.html', context)
        return HttpResponseForbidden()


class ClassroomListView(LoginRequiredMixin, View):
    """Отображение списка классов с возможностью фильтрации по выпуску"""

    def get(self, request):
        graduated = request.GET.get('graduated') == '1'
        classrooms = Classroom.objects.filter(is_graduated=graduated, school=request.user.school).order_by('number', 'letter')
        context_title = "Выпустившиеся классы" if graduated else "Текущие классы"
        return render(request, 'list_classroom/list_classroom.html', {
            'classrooms': classrooms,
            'graduated': graduated,
            'context_title': context_title
        })


class PromoteAllClassroomsView(LoginRequiredMixin, View):
    """Продвижение всех классов на следующий уровень"""

    def get(self, request):
        return render(request, 'list_classroom/promote_all_classrooms_confirm.html')

    def post(self, request):
        classrooms = Classroom.objects.filter(is_graduated=False, school=request.user.school)
        for classroom in classrooms:
            classroom.promote()
        messages.success(request, 'Все классы успешно продвинуты.')
        return redirect('classroom:list_classroom')


class ChildClassroomListAdmin(LoginRequiredMixin, AdminRequiredMixin, View):
    """Отображение списка детей для администратора в конкретном классе"""

    def get(self, request, Classroom_id):
        classroom = get_object_or_404(Classroom, id=Classroom_id, school=request.user.school)
        classroom_children = User.objects.filter(classroom_id=Classroom_id, school=request.user.school)
        context = {
            'classroom': classroom,
            'children': classroom_children
        }
        return render(request, 'children_list_admin/children_list_admin.html', context)


class ChildExpelAdmin(LoginRequiredMixin, View):
    """Исключение ученика администратором"""

    def post(self, request, User_id):
        user = get_object_or_404(User, id=User_id, school=request.user.school)
        user.is_expelled = True
        user.save()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ChildReinstateAdmin(LoginRequiredMixin, View):
    """Восстановление ученика администратором"""

    def post(self, request, User_id):
        user = get_object_or_404(User, id=User_id, school=request.user.school)
        user.is_expelled = False
        user.save()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ChildRemoveAdmin(LoginRequiredMixin, View):
    """Удаление ученика администратором"""

    def get(self, request, User_id):
        user = get_object_or_404(User, id=User_id, school=request.user.school)
        user.delete()
        return HttpResponseRedirect(request.META['HTTP_REFERER'])


class ClassroomCreateView(LoginRequiredMixin, CreateView):
    """Создание нового класса"""

    model = Classroom
    form_class = ClassroomForm
    template_name = 'classroom_add/classroom_form.html'
    success_url = reverse_lazy('classroom:list_classroom')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_students'] = User.objects.filter(is_child=True, school=self.request.user.school)
        return context

    def form_valid(self, form):
        form.instance.school = self.request.user.school
        response = super().form_valid(form)
        students_ids = self.request.POST.getlist('students')
        students = User.objects.filter(id__in=students_ids, is_child=True, school=self.request.user.school)
        self.object.child.set(students)
        return response


class ClassroomUpdateView(LoginRequiredMixin, UpdateView):
    """Обновление информации о классе"""

    model = Classroom
    form_class = ClassroomForm
    template_name = 'classroom_add/classroom_form.html'
    success_url = reverse_lazy('classroom:list_classroom')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_students'] = User.objects.filter(is_child=True, school=self.request.user.school)
        context['class_students'] = self.get_class_students()
        return context

    def get_class_students(self):
        classroom_id = self.kwargs.get('pk')
        if classroom_id:
            classroom = get_object_or_404(Classroom, pk=classroom_id, school=self.request.user.school)
            return classroom.child.all()
        return User.objects.none()

    def form_valid(self, form):
        form.instance.school = self.request.user.school
        response = super().form_valid(form)
        students_ids = self.request.POST.getlist('students')
        students = User.objects.filter(id__in=students_ids, is_child=True, school=self.request.user.school)
        self.object.child.set(students)
        return response


class ClassroomDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление класса"""

    model = Classroom
    template_name = 'classroom_add/classroom_confirm_delete.html'
    success_url = reverse_lazy('classroom:list_classroom')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_students'] = User.objects.filter(is_child=True, school=self.request.user.school)
        return context

    def get_class_students(self):
        classroom_id = self.kwargs.get('pk')
        if classroom_id:
            classroom = get_object_or_404(Classroom, pk=classroom_id, school=self.request.user.school)
            return classroom.child.all()
        return User.objects.none()

olympiad/classroom/templates/children_list_admin/children_list_admin.html
{% extends 'base_olimp.html' %}
{% load static %}
{% block content %}
    <div class="mb-4">
        <h1 class="text-3xl font-bold">Список учеников</h1>
        <h2 class="text-xl text-gray-600">Класс: {{ classroom.number }} {{ classroom.letter }}</h2>
    </div>

    <div class="flex justify-between mb-4">
        <a class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600" href="{% url 'users:CreateChild' %}">Добавить ученика</a>
    </div>

    <div class="overflow-x-auto bg-white shadow-md rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider ">
                    ID
                </th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    ФИО
                </th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Пол
                </th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Дата рождения
                </th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Действия
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            {% for child in children %}
                <tr class="{% if child.is_expelled %}bg-gray-300{% endif %}">
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-center">
                        {{ child.id }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">
                        {{ child.last_name }} {{ child.first_name }} {{ child.surname }}
                        {% if child.is_expelled %}
                            <span class="text-red-500">(Исключен)</span>
                        {% endif %}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-center">
                        {{ child.gender }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-center">
                        {{ child.birth_date }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-center">
                        {% if not child.is_expelled %}
                            <button onclick="openModal('{{ child.id }}')" class="text-white border-2 h-8 w-32 rounded-lg bg-yellow-300 font-medium hover:inner-shadow hover:bg-white hover:text-yellow-300 border-yellow-300 transition duration-500">Редактировать</button>
                            <button onclick="openModal('{{ child.id }}')" class="text-white border-2 h-8 w-32 rounded-lg bg-red-400 font-medium hover:inner-shadow hover:bg-white hover:text-red-400 border-red-400 transition duration-500">Удалить</button>

                        {% else %}
                            <form method="post" action="{% url 'classroom:child_reinstate_admin' child.id %}">
                                {% csrf_token %}
                                <button type="submit" class="text-green-600 hover:text-green-900">Восстановить</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Modal -->
    <div id="expelModal" class="fixed inset-0 flex items-center justify-center bg-gray-600 bg-opacity-50 hidden">
        <div class="bg-white p-6 rounded shadow-lg">
            <h2 class="text-xl mb-4">Вы уверены, что хотите исключить этого ученика?</h2>
            <div class="flex justify-end">
                <button onclick="closeModal()" class="bg-gray-300 text-black px-4 py-2 rounded mr-2">Отмена</button>
                <form id="expelForm" method="post">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-600 text-white px-4 py-2 rounded">Исключить</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        function openModal(childId) {
            const modal = document.getElementById('expelModal');
            const form = document.getElementById('expelForm');
            form.action = `{% url 'classroom:child_expel_admin' '0' %}`.replace('0', childId);
            modal.classList.remove('hidden');
        }

        function closeModal() {
            const modal = document.getElementById('expelModal');
            modal.classList.add('hidden');
        }
    </script>
{% endblock %}