olympiad/api/urls.py
from django.urls import path
from .views import login_view
app_name = 'api'


urlpatterns = [
    path('api/login/', login_view, name='api-login'),
]

olympiad/docs/urls.py
from django.urls import path
from .views import *


app_name = 'docs'
urlpatterns = [
    path('export/excel/', ExcelAll.as_view(), name='zayvki_export_excel'),
    path('export/excel/classroom/<int:Classroom_id>/', ExcelClassroom.as_view(), name='excel_classroom'),
    path('export/dashboard/', ExportExcelView.as_view(), name='export_excel_result'),
    path('import/users', ImportUsersView.as_view(), name='import_users'),
    path('import_olympiads/', ImportOlympiadsView.as_view(), name='import_olympiads'),
    path('download/zip/', CreateZipArchive.as_view(), name='download_applications_zip'),
    path('download/teacher/zip/', CreateZipArchiveForTeacher.as_view(), name='download_teacher_applications_zip'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/export/', ExportExcelView.as_view(), name='export_excel'),
    path('success/', lambda request: render(request, 'docs/succes_import.html'), name='succes_import'),
    path('success/olympiad', lambda request: render(request, 'docs/succes_import_olympiad.html'), name='succes_import_olympiad'),


]

olympiad/olympiad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import StartPage
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('silk/', include('silk.urls', namespace='silk')),
    # Пока нет главной страницы, перенаправление на страницу входа
    path('', StartPage.as_view(), name='start_page'),
    # Главное приложение
    path('main/', include('main.urls', namespace='main')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('register/', include('register.urls', namespace='register')),
    path('result/', include('result.urls', namespace='result')),
    path('school/', include('school.urls', namespace='school')),
    path('classroom/', include('classroom.urls', namespace='classroom')),
    path('calendar/', include('calendar_olimp.urls', namespace='calendar')),
    # Приложения авторизации
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('chat/', include('chat.urls')),
]

# Обработка медиафайлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Обработка ошибки 404
handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

olympiad/docs/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField(label='Выберите файл')

olympiad/docs/views.py
import logging
import os
import tempfile
import zipfile

import pandas as pd
import pymorphy3
from django.db import transaction
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponseBadRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import ListView
from openpyxl import Workbook
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

from classroom.models import *
from main.models import *
from register.models import RegisterAdmin, RegisterSend
from result.models import *
from users.mixins import AdminRequiredMixin
from users.models import User
from .forms import UploadFileForm

logger = logging.getLogger(__name__)


class ExcelClassroom(AdminRequiredMixin, View):
    """Создание Excel файла с данными о классах"""

    def get(self, request, Classroom_id):
        if not request.user.is_admin:
            return HttpResponseForbidden()

        classroom = get_object_or_404(Classroom, id=Classroom_id, school=request.user.school)
        queryset = RegisterAdmin.objects.filter(
            child_admin__classroom__id=Classroom_id, is_deleted=False, school=request.user.school)

        data_classroom = [
            [_("№"), _("Фамилия"), _("Имя"), _("Отчество"), _("Пол"), _("Дата рождения (формат 01.08.98)"),
             _("Статус наличия гражданства"), _("Участник с ОВЗ"), _("Краткое наименование ОУ"),
             _("Класс, в котором учится участник"), _("Буква класса, в котором учится участник"),
             _("Английский язык (4, 5-6, 7-8, 9-11)"), _("География (5, 6, 7, 8, 9, 10-11)"),
             _("Информатика (3, 4)"), _("Искусство (МХК) (5, 6, 7, 8, 9, 10, 11)"), _("История (5, 6, 7, 8, 9, 10-11)"),
             _("Литература (5, 6, 7, 8, 9, 10, 11)"), _("Музыка (5, 6, 7, 8)"), _("Немецкий язык (4, 5-6, 7-8, 9-11)"),
             _("Обществознание (5, 6, 7, 8, 9, 10, 11)"), _("ОБЖ (5, 6, 7, 8, 9, 10-11)"), _("Право (9, 10, 11)"),
             _("Психология (7-11)"), _("Русский язык (5, 6, 7, 8, 9, 10, 11)"), _("Технология (5-6, 7-8, 9, 10-11)"),
             _("Физика (5, 6)"), _("Физическая культура (5-6, 7-8, 9-11)"), _("Французский язык (4, 5-6, 7-8, 9-11)"),
             _("Экология (7, 8, 9, 10, 11)"), _("Экономика (7-9, 10-11)"), _("НШ: литературное чтение (4)"),
             _("НШ: окружающий мир (4)"), _("НШ: русский язык (4)"), _("НШ: математика (4)"),
             _("Математика (5, 6, 7, 8, 9, 10, 11)"), _("Кол-во заявлений")],
        ]

        student_data = {}

        for obj in queryset:
            student_id = obj.child_admin.id
            if student_id not in student_data:
                student_data[student_id] = {
                    "last_name": obj.child_admin.last_name,
                    "first_name": obj.child_admin.first_name,
                    "surname": obj.child_admin.surname,
                    "gender": obj.child_admin.gender,
                    "birth_date": obj.child_admin.birth_date,
                    "class_number": obj.child_admin.classroom.number,
                    "class_letter": obj.child_admin.classroom.letter,
                    "subjects": {subject: 0 for subject in [
                        "Английский язык", "География", "Информатика", "Искусство (МХК)", "История", "Литература",
                        "Музыка", "Немецкий язык", "Обществознание", "ОБЖ", "Право", "Психология", "Русский язык",
                        "Технология", "Физика", "Физическая культура", "Французский язык", "Экология", "Экономика",
                        "НШ: литературное чтение", "НШ: окружающий мир", "НШ: русский язык", "НШ: математика",
                        "Математика"
                    ]}
                }

            student_data[student_id]["subjects"][obj.olympiad_admin.subject.name] = 1

        for student_id, student_info in student_data.items():
            subjects = student_info["subjects"]
            data_classroom.append([
                student_id,
                student_info["last_name"],
                student_info["first_name"],
                student_info["surname"],
                student_info["gender"],
                student_info["birth_date"],
                'РФ',
                '',
                'МАОУ «МЛ № 1»',
                student_info["class_number"],
                student_info["class_letter"],
                subjects["Английский язык"],
                subjects["География"],
                subjects["Информатика"],
                subjects["Искусство (МХК)"],
                subjects["История"],
                subjects["Литература"],
                subjects["Музыка"],
                subjects["Немецкий язык"],
                subjects["Обществознание"],
                subjects["ОБЖ"],
                subjects["Право"],
                subjects["Психология"],
                subjects["Русский язык"],
                subjects["Технология"],
                subjects["Физика"],
                subjects["Физическая культура"],
                subjects["Французский язык"],
                subjects["Экология"],
                subjects["Экономика"],
                subjects["НШ: литературное чтение"],
                subjects["НШ: окружающий мир"],
                subjects["НШ: русский язык"],
                subjects["НШ: математика"],
                subjects["Математика"],
            ])

        return self.generate_excel_response(data_classroom, f'Zayvki {classroom.number}{classroom.letter} classa')

    def generate_excel_response(self, data, filename):
        """Генерация Excel файла и отправка в ответе"""
        wb = Workbook()
        ws = wb.active

        for row in data:
            ws.append(row)

        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = f'attachment; filename="{filename}.xlsx"'
        wb.save(response)
        return response


class ExcelAll(AdminRequiredMixin, View):
    """Создание Excel файла со всеми данными"""

    def get(self, request):
        if not request.user.is_admin:
            return HttpResponseForbidden()

        queryset = RegisterAdmin.objects.filter(is_deleted=False, school=request.user.school)

        data_all = [
            [_("№"), _("Фамилия"), _("Имя"), _("Отчество"), _("Пол"), _("Дата рождения (формат 01.08.98)"),
             _("Статус наличия гражданства"), _("Участник с ОВЗ"), _("Краткое наименование ОУ"),
             _("Класс, в котором учится участник"), _("Буква класса, в котором учится участник"),
             _("Английский язык (4, 5-6, 7-8, 9-11)"), _("География (5, 6, 7, 8, 9, 10-11)"),
             _("Информатика (3, 4)"), _("Искусство (МХК) (5, 6, 7, 8, 9, 10, 11)"), _("История (5, 6, 7, 8, 9, 10-11)"),
             _("Литература (5, 6, 7, 8, 9, 10, 11)"), _("Музыка (5, 6, 7, 8)"), _("Немецкий язык (4, 5-6, 7-8, 9-11)"),
             _("Обществознание (5, 6, 7, 8, 9, 10, 11)"), _("ОБЖ (5, 6, 7, 8, 9, 10-11)"), _("Право (9, 10, 11)"),
             _("Психология (7-11)"), _("Русский язык (5, 6, 7, 8, 9, 10, 11)"), _("Технология (5-6, 7-8, 9, 10-11)"),
             _("Физика (5, 6)"), _("Физическая культура (5-6, 7-8, 9-11)"), _("Французский язык (4, 5-6, 7-8, 9-11)"),
             _("Экология (7, 8, 9, 10, 11)"), _("Экономика (7-9, 10-11)"), _("НШ: литературное чтение (4)"),
             _("НШ: окружающий мир"), _("НШ: русский язык"), _("НШ: математика"),
             _("Математика (5, 6, 7, 8, 9, 10, 11)"), _("Кол-во заявлений")],
        ]

        student_data = {}

        for obj in queryset:
            student_id = obj.child_admin.id
            if student_id not in student_data:
                student_data[student_id] = {
                    "last_name": obj.child_admin.last_name,
                    "first_name": obj.child_admin.first_name,
                    "surname": obj.child_admin.surname,
                    "gender": obj.child_admin.gender,
                    "birth_date": obj.child_admin.birth_date,
                    "class_number": obj.child_admin.classroom.number,
                    "class_letter": obj.child_admin.classroom.letter,
                    "subjects": {subject: 0 for subject in [
                        "Английский язык", "География", "Информатика", "Искусство (МХК)", "История", "Литература",
                        "Музыка", "Немецкий язык", "Обществознание", "ОБЖ", "Право", "Психология", "Русский язык",
                        "Технология", "Физика", "Физическая культура", "Французский язык", "Экология", "Экономика",
                        "НШ: литературное чтение", "НШ: окружающий мир", "НШ: русский язык", "НШ: математика",
                        "Математика"
                    ]}
                }

            student_data[student_id]["subjects"][obj.olympiad_admin.subject.name] = 1

        for student_id, student_info in student_data.items():
            subjects = student_info["subjects"]
            data_all.append([
                student_id,
                student_info["last_name"],
                student_info["first_name"],
                student_info["surname"],
                student_info["gender"],
                student_info["birth_date"],
                'РФ',
                '',
                'МАОУ «МЛ № 1»',
                student_info["class_number"],
                student_info["class_letter"],
                subjects["Английский язык"],
                subjects["География"],
                subjects["Информатика"],
                subjects["Искусство (МХК)"],
                subjects["История"],
                subjects["Литература"],
                subjects["Музыка"],
                subjects["Немецкий язык"],
                subjects["Обществознание"],
                subjects["ОБЖ"],

olympiad/docs/templates/dashboard.html
{% extends 'base_olimp.html' %}
{% load static %}
{% block content %}
    {% block head_olimp %}
        <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet"/>
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/tailwind.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" rel="stylesheet">
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ru.js"></script>
    <script>
        $(document).ready(function () {
            $('.select2').select2({
                theme: 'default'
            });

            flatpickr.localize(flatpickr.l10ns.ru);
            flatpickr("#start-date", {
                dateFormat: "d-m-Y",
                locale: "ru"
            });
            flatpickr("#end-date", {
                dateFormat: "d-m-Y",
                locale: "ru"
            });
        });
    </script>

    <div class="container mx-auto p-6 bg-white shadow-lg rounded-lg">
        <h2 class="text-2xl font-bold mb-4">Фильтр результатов</h2>
        <form method="get" id="filterForm" class="space-y-4">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div>
                    <label for="start-date" class="block text-gray-700">Начальная дата</label>
                    <input type="text" id="start-date" name="start-date" value="{{ start_date }}"
                           class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                </div>

                <div>
                    <label for="end-date" class="block text-gray-700">Конечная дата</label>
                    <input type="text" id="end-date" name="end-date" value="{{ end_date }}"
                           class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                </div>

                <div>
                    <label for="class" class="block text-gray-700">Класс</label>
                    <select id="class" name="class" class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                        <option value="">Выберите класс</option>
                        {% for class in classrooms %}
                            <option value="{{ class.id }}"
                                    {% if class.id|stringformat:"s" == class_filter %}selected{% endif %}>
                                {{ class.number }}{{ class.letter }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div>
                    <label for="parallel" class="block text-gray-700">Параллель</label>
                    <select id="parallel" name="parallel" class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                        <option value="">Выберите параллель</option>
                        {% for parallel in parallels %}
                            <option value="{{ parallel }}"
                                    {% if parallel|stringformat:"s" == parallel_filter %}selected{% endif %}>
                                {{ parallel }} параллель
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div>
                    <label for="subject" class="block text-gray-700">Предмет</label>
                    <select id="subject" name="subject" class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                        <option value="">Выберите предмет</option>
                        {% for subject in subjects %}
                            <option value="{{ subject.id }}"
                                    {% if subject.id|stringformat:"s" == subject_filter %}selected{% endif %}>
                                {{ subject.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div>
                    <label for="student" class="block text-gray-700">Ученик</label>
                    <select id="student" name="student" class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                        <option value="">Выберите ученика</option>
                        {% for user in students %}
                            <option value="{{ user.id }}"
                                    {% if user.id|stringformat:"s" == student_filter %}selected{% endif %}>
                                {{ user.get_full_name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div>
                    <label for="olympiad" class="block text-gray-700">Олимпиада</label>
                    <select id="olympiad" name="olympiad" class="focus:outline-none focus:bg-gray-200 transition duration-500 h-9 bg-gray-100 pl-3 mt-1 block w-full rounded-md border-gray-300 shadow-inner">
                        <option value="">Выберите олимпиаду</option>
                        {% for olympiad in olympiads %}
                            <option value="{{ olympiad.id }}"
                                    {% if olympiad.id|stringformat:"s" == olympiad_filter %}selected{% endif %}>
                                {{ olympiad.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="mt-4 flex space-x-4">
                <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700">
                    Применить фильтр
                </button>
                <a href="{% url 'docs:export_excel' %}?start-date={{ start_date }}&end-date={{ end_date }}&class={{ class_filter }}&subject={{ subject_filter }}&student={{ student_filter }}&olympiad={{ olympiad_filter }}"
                   class="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-700">
                    Выгрузить Excel
                </a>
            </div>
        </form>
    </div>

    <div class="container mx-auto mt-8 bg-white shadow-lg rounded-lg p-6">
        <h2 class="text-2xl font-bold mb-4">Результаты</h2>
        <p>Победителей: {{ winners_count }}</p>
        <p>Призеров: {{ prizewinners_count }}</p>
        <p>Участников: {{ participants_count }}</p>
        <table class="min-w-full bg-white divide-y divide-gray-200 mt-5">
            <thead class="bg-gray-50">
            <tr>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Ученик</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Олимпиада</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Предмет</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Класс</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Очки</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Статус</th>
                <th class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase  tracking-wider">Дата</th>
            </tr>
            </thead>
            <tbody>
            {% for result in results %}
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.info_children.get_full_name }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.info_olympiad.name }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.info_olympiad.subject.name }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.info_children.classroom.number }} {{ result.info_children.classroom.letter }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.points }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.get_status_result_display }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 text-center">{{ result.date_added|date:"d-m-Y" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

olympiad/docs/templates/import_olympiads.html
{% extends 'base_olimp.html' %}
{% block content %}
<div class="container mx-auto p-6 bg-white shadow-lg rounded-lg">
    <h1 class="text-2xl font-bold mb-4">Импорт олимпиад из Excel файла</h1>
    <form method="post" enctype="multipart/form-data" class="space-y-4">
        {% csrf_token %}

        <!-- Отображение общих ошибок формы -->
        {% if form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <strong class="font-bold">Ошибки:</strong>
            <span class="block sm:inline">{{ form.non_field_errors }}</span>
        </div>
        {% endif %}

        {{ form.as_p }}

        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Загрузить</button>
    </form>
</div>
{% endblock %}

olympiad/docs/templates/succes_import.html
{% extends 'base_olimp.html' %}
{% load static %}
{% block content %}
    <h1>Импорт завершен успешно</h1>
    <p>Пользователи успешно импортированы в базу данных.</p>
    <a href="{% url 'docs:import_users' %}">Вернуться к форме импорта</a>
{% endblock content %}

olympiad/docs/templates/upload.html
{% extends 'base_olimp.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto p-6 bg-white shadow-lg rounded-lg">
    <h1 class="text-2xl font-bold mb-4">Загрузить файл</h1>
    <form method="post" enctype="multipart/form-data" class="space-y-4">
        {% csrf_token %}

        <!-- Отображение общих ошибок формы -->
        {% if form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <strong class="font-bold">Ошибки:</strong>
            <span class="block sm:inline">{{ form.non_field_errors }}</span>
        </div>
        {% endif %}

        <div>
            {{ form.file }}
            {% if form.file.errors %}
            <p class="text-red-500 text-xs italic">{{ form.file.errors }}</p>
            {% endif %}
        </div>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Загрузить</button>
    </form>
</div>
{% endblock %}

olympiad/docs/templates/upload_docs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Загрузка пользователей</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
</head>
<body class="bg-gray-100">
<div class="container mx-auto p-6 bg-white shadow-md rounded-lg mt-6">
    <h1 class="text-2xl font-bold mb-4">Загрузка пользователей</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Отображение общих ошибок формы -->
        {% if form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
            <strong class="font-bold">Ошибки:</strong>
            <span class="block sm:inline">{{ form.non_field_errors }}</span>
        </div>
        {% endif %}

        {{ form.as_p }}

        <!-- Обработка ошибок для поля файла -->
        <div>
            {{ form.file }}
            {% if form.file.errors %}
            <p class="text-red-500 text-xs italic">{{ form.file.errors }}</p>
            {% endif %}
        </div>

        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 mt-4">Загрузить</button>
    </form>

    <!-- Отображение ошибок -->
    {% if errors %}
        <div class="mt-6">
            <h2 class="text-xl font-semibold text-red-500">Ошибки:</h2>
            <ul class="list-disc list-inside text-red-500">
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>
</body>
</html>