olympiad/api/urls.py
from django.urls import path
from .views import login_view
app_name = 'api'


urlpatterns = [
    path('api/login/', login_view, name='api-login'),
]

olympiad/main/urls.py
from django.urls import path
from .views import HomePageView, OlympiadListView, OlympiadCreateView, OlympiadUpdateView, OlympiadDeleteView, AuditLogView

app_name = 'main'

urlpatterns = [
    # Главная страница
    path('', HomePageView.as_view(), name='home'),

    # Страницы для администратора
    path('olympiad/list/', OlympiadListView.as_view(), name='list_olympiad'),
    path('olympiad/new/', OlympiadCreateView.as_view(), name='olympiad_create'),
    path('olympiad/edit/<int:pk>/', OlympiadUpdateView.as_view(), name='olympiad_update'),
    path('olympiad/delete/<int:pk>/', OlympiadDeleteView.as_view(), name='olympiad_delete'),
    path('audit/', AuditLogView.as_view(), name='audit_log'),
]

olympiad/olympiad/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from users.views import StartPage
from main.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('silk/', include('silk.urls', namespace='silk')),
    # Пока нет главной страницы, перенаправление на страницу входа
    path('', StartPage.as_view(), name='start_page'),
    # Главное приложение
    path('main/', include('main.urls', namespace='main')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('register/', include('register.urls', namespace='register')),
    path('result/', include('result.urls', namespace='result')),
    path('school/', include('school.urls', namespace='school')),
    path('classroom/', include('classroom.urls', namespace='classroom')),
    path('calendar/', include('calendar_olimp.urls', namespace='calendar')),
    # Приложения авторизации
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('friends/', include('friends.urls', namespace='friends')),
    path('chat/', include('chat.urls')),
]

# Обработка медиафайлов в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Обработка ошибки 404
handler400 = bad_request
handler403 = permission_denied
handler404 = page_not_found
handler500 = server_error

olympiad/register/urls.py
from django.urls import path
from .views import *

app_name = 'register'

urlpatterns = [
    # Регистрация на олимпиаду
    path('olympiad/', RegisterPage.as_view(), name='register-olympiad'),
    path('olympiad/add/<int:Olympiad_id>/', RegisterAdd.as_view(), name='register_add'),
    path('olympiad/delete/<int:Register_id>/', RegisterDelete.as_view(), name='register_remove'),

    # Корзина заявок студентов
    path('basket/student/', BasketStudentApp.as_view(), name='basket-student-applications'),

    # Отправка заявки
    path('send/', RegisterSendChild.as_view(), name='register_send'),
    path('send/teacher/', RegisterSendTeacher.as_view(), name='register_send_teacher'),

    # Список заявок студентов
    path('child/list/', ChildRegisterList.as_view(), name='student-applications'),

    # Удаление заявки учителем
    path('delete/<int:Olympiad_id>/<int:student_id>/', RegisterDeleteTeacher.as_view(), name='register_delete_teacher'),

    # Рекомендации от учителя
    path('teacher/recommendations/', TeacherRecommendationsView.as_view(), name='teacher_recommendations'),
    path('add-recommendation/', AddRecommendation.as_view(), name='add_recommendation'),

    # Обработка рекомендаций
    path('register/accept_recommendation/<int:recommendation_id>/', accept_recommendation,
         name='accept_recommendation'),
    path('register/reject_recommendation/<int:recommendation_id>/', reject_recommendation,
         name='reject_recommendation'),

    # Заявки от учителей по классам
    path('applications/classroom/teachers/', RegisterListClassroom.as_view(),
         name='applications-from-classroom-teachers'),

    # Получение олимпиад для студента
    path('get-olympiads-for-student/', GetOlympiadsForStudent.as_view(), name='get_olympiads_for_student'),

    # Добавление заявки
    path('add_register/', AddRegister.as_view(), name='add_register'),

    # Получение студентов для класса
    path('get-students-for-classroom/', GetStudentsForClassroomView.as_view(), name='get_students_for_classroom'),

    # Получение олимпиад для студента
    path('get-olympiads-for-student/', GetOlympiadsForStudentView.as_view(), name='get_olympiads_for_student'),
]

olympiad/main/models.py
from django.db import models


class AuditLog(models.Model):
    """
    Модель для ведения журнала аудита действий пользователей.
    """
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Пользователь')
    action = models.CharField(max_length=256, verbose_name='Действие')
    object_name = models.CharField(max_length=256, verbose_name='Объект')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Время действия')
    school = models.ForeignKey('school.School', on_delete=models.CASCADE, verbose_name='Школа',
                               related_name='school_audit')

    def __str__(self):
        return f'{self.user} - {self.action} - {self.object_name}'


class Subject(models.Model):
    """
    Модель учебных предметов. Пример: Информатика.
    """

    class Meta:
        verbose_name_plural = "Школьные предметы"
        verbose_name = 'Школьный предмет'

    name = models.CharField('Название школьного предмета', max_length=256, unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    """
    Модель категорий олимпиад. Пример: ВСОШ.
    """

    class Meta:
        verbose_name_plural = "Категории олимпиад"
        verbose_name = 'Категория олимпиад'

    name = models.CharField('Название категории', max_length=256)

    def __str__(self):
        return self.name


class LevelOlympiad(models.Model):
    """
    Модель уровней олимпиад. Пример: Муниципальный.
    """

    class Meta:
        verbose_name_plural = "Уровень олимпиад"
        verbose_name = 'Уровень олимпиад'

    name = models.CharField('Название уровня', max_length=256)

    def __str__(self):
        return self.name


class Stage(models.Model):
    """
    Модель этапов олимпиад. Пример: Школьный.
    """

    class Meta:
        verbose_name_plural = "Этапы олимпиад"
        verbose_name = 'Этап олимпиады'

    name = models.CharField('Название категории', max_length=256)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    Модель должностей персонала школы. Пример: Учитель.
    """

    class Meta:
        verbose_name_plural = "Должности"
        verbose_name = 'Должность'

    name = models.CharField('Должность', max_length=512)

    def __str__(self):
        return self.name


class Olympiad(models.Model):
    """
    Модель олимпиады.
    """

    class Meta:
        verbose_name_plural = "Олимпиады"
        verbose_name = 'Олимпиада'

    name = models.CharField('Название олимпиады', max_length=256)
    description = models.TextField('Описание олимпиады', blank=True, null=True)
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, verbose_name='Категория олимпиады')
    level = models.ForeignKey(to='LevelOlympiad', on_delete=models.CASCADE, verbose_name='Название уровня')
    stage = models.ForeignKey(to='Stage', on_delete=models.CASCADE, verbose_name='Название этапа')
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE, verbose_name='Название школьного предмета')
    class_olympiad = models.IntegerField('Класс олимпиады')
    date = models.DateField('Дата проведения', blank=True, null=True)
    time = models.TimeField('Время проведения', blank=True, null=True)
    location = models.CharField('Место проведения олимпиады', max_length=256, blank=True, null=True)

    def __str__(self):
        return f'{self.name} - {self.stage} - {self.subject} {self.class_olympiad}'

olympiad/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from register.models import RegisterAdmin
from result.models import Result
from main.models import Olympiad


class OlympiadForm(forms.ModelForm):
    """
    Форма для создания и редактирования олимпиады.
    Использует модель Olympiad и включает все ее поля.
    """

    class Meta:
        model = Olympiad
        fields = '__all__'
        labels = {
            'name': 'Название олимпиады',
            'description': 'Описание олимпиады',
            'category': 'Категория олимпиады',
            'level': 'Уровень олимпиады',
            'stage': 'Этап олимпиады',
            'subject': 'Школьный предмет',
            'class_olympiad': 'Класс олимпиады',
            'date': 'Дата проведения',
            'time': 'Время проведения',
            'location': 'Место проведения',
        }
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

olympiad/main/views.py
from django.http import HttpResponseNotFound
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from result.models import Result
from raiting_system.models import Rating, Medal, PersonalMedal
from .forms import OlympiadForm
from .filters import OlympiadFilter
from .models import AuditLog, Olympiad


def bad_request(request, exception):
    return render(request, 'errors/errore400.html', status=400)


def permission_denied(request, exception):
    return render(request, 'errors/errore403.html', status=403)


def page_not_found(request, exception):
    return render(request, 'errors/errore404.html', status=404)


def server_error(request):
    return render(request, 'errors/errore500.html', status=500)


class HomePageView(LoginRequiredMixin, TemplateView):
    """
    Представление для главной страницы.
    """
    template_name = 'homepage/homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получение последних 10 результатов для текущего пользователя
        recent_results = Result.objects.filter(info_children=self.request.user,
                                               school=self.request.user.school).order_by('-date_added')[:10]
        context['recent_results'] = recent_results

        # Получение рейтинга пользователя
        user_rating = Rating.objects.filter(user=self.request.user).first()
        context['user_rating'] = user_rating

        # Расчеты для лиг
        points = user_rating.points if user_rating else 0
        league, points_to_next = self.calculate_league(points)
        context['league'] = league
        context['points_to_next'] = points_to_next

        # Получение медалей пользователя
        user_medals = Medal.objects.filter(user=self.request.user)
        context['user_medals'] = user_medals

        # Получение именных медалей пользователя
        user_personal_medals = PersonalMedal.objects.filter(user=self.request.user)
        context['user_personal_medals'] = user_personal_medals

        # Получение олимпиад
        olympiads = Olympiad.objects.order_by('date')
        context['olympiads'] = olympiads

        return context

    def calculate_league(self, points):
        """
        Вспомогательный метод для расчета лиги и очков до следующей лиги.
        """
        if points <= 150:
            return 'Бронзовая лига', 151 - points
        elif points <= 500:
            return 'Серебряная лига', 501 - points
        elif points <= 1000:
            return 'Золотая лига', 1001 - points
        elif points <= 2000:
            return 'Платиновая лига', 2001 - points
        elif points <= 3500:
            return 'Рубиновая лига', 3501 - points
        else:
            return 'Алмазная лига', 0


class AuditLogView(LoginRequiredMixin, ListView):
    """
    Представление для отображения журнала аудита.
    """
    paginate_by = 5
    model = AuditLog
    template_name = 'audit_log/audit_log.html'
    context_object_name = 'audit_logs'
    ordering = ['-timestamp']

    def get_queryset(self):
        # Отображаем только для администраторов
        if self.request.user.is_admin:
            return super().get_queryset()
        else:
            return AuditLog.objects.none()


class OlympiadListView(ListView):
    """
    Представление для отображения списка олимпиад.
    """
    model = Olympiad
    template_name = 'list_olympiad/list_olympiad.html'
    context_object_name = 'olympiads'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = OlympiadFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class OlympiadCreateView(CreateView):
    """
    Представление для создания новой олимпиады.
    """
    model = Olympiad
    form_class = OlympiadForm
    template_name = 'list_olympiad/olympiad_form.html'
    success_url = reverse_lazy('main:list_olympiad')


class OlympiadUpdateView(UpdateView):
    """
    Представление для обновления существующей олимпиады.
    """
    model = Olympiad
    form_class = OlympiadForm
    template_name = 'list_olympiad/olympiad_form.html'
    success_url = reverse_lazy('main:list_olympiad')


class OlympiadDeleteView(DeleteView):
    """
    Представление для удаления олимпиады.
    """
    model = Olympiad
    template_name = 'list_olympiad/olympiad_confirm_delete.html'
    success_url = reverse_lazy('main:list_olympiad')

olympiad/main/templates/student-applications/student-applications.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'student-applications/student-applications.css' %}" id="them">
    <title>Olimp | Заявки вашего класса</title>
</head>
<header>
    <div class="golova">
        <img class="logo" id="l-tip" src="{% static 'student-applications/img/logoolimp.jpg' %}">
        <p class="logoword">Olimp</p>
        <p class="wordhead">Заявки учеников</p>
        <div id="sun">
            <button class="solnce"><img class="sun" id="sunw" src="{% static 'student-applications/img/sun.png' %}">
            </button>
        </div>
        <div id="yourlogo">
            <button class="avatarka"><img class="sun" id="avatarka"
                                          src="{% static 'student-applications/img/avatarka.png' %}">
            </button>
        </div>
        <div id="chat">
            <button class="chatik"><img class="sun" id="chatblack"
                                        src="{% static 'student-applications/img/chatblack.png' %}">
            </button>
        </div>
    </div>
</header>
<body>
{% include 'navbar/navbar.html' %}
{% block content %}
{% endblock %}


<div class="main">
    <div class="toptext">
        <h1 class="toptext1">Заявки учеников</h1>
        <h2 class="toptext2">Класс {{ user.classroom_guide.number }}{{ user.classroom_guide.letter }}</h2>
    </div>
    <div class="topbuttons">
        <a class="buttonspispeople" type="submit">Список участников</a>
        <a class="buttonsend" href="{% url 'main:register_send_teacher' %}">Отправить заявку</a>
        <a class="buttonadd" href="/admin/main/register/add/">Добавить ученика</a>
    </div>
    <div class="tablespisok">
        <div class="zagolovok">
            <table class="mainspisokpoepletable">
                <th>
                    <div id="textid">ID</div>
                </th>
                <th>
                    <div id="textychenik">Ученик</div>
                </th>
                <th>
                    <div id="textolimp">Олимпиада</div>
                </th>
                <th>
                    <div id="textstage">Этап</div>
                </th>
                <th>
                    <div id="textgender">Пол</div>
                </th>
                <th>
                    <div id="textdate">Дата рождения</div>
                </th>
                <th>
                    <div id="textdeistie">Действие</div>
                </th>
            </table>

        </div>

        {% for student, olympiads in student_olympiads.items %}
            <div class="mainspisokpoeple">
            <div class="nameid">{{ student.id }}</div>
            <div class="namefio">{{ student.last_name }} {{ student.first_name }} {{ student.surname }}</div>
            <table class="tableolimps">
            <td>
            <th>
            {% for olympiad in olympiads %}
                <div class="olimps">
                    <li>
                        {{ olympiad.name }} (ID: {{ olympiad.id }})
                        <form method="post" action="{% url 'main:delete_register' olympiad.id student.id %}"
                              style="display:inline;">
                            {% csrf_token %}
                            <button type="submit">Удалить</button>
                        </form>
                    </li>
                </div>
            {% endfor %}
        {% endfor %}
        </th>
        </td>
        </table>
        </div>



        {#{% for student, olympiads in student_olympiads.items %}#}
        {#    <li>#}
        {#        <strong>{{ student.get_full_name }} (ID: {{ student.id }})</strong>#}
        {#        <ul>#}
        {#                    {% for olympiad in olympiads %}#}
        {#                        <li>#}
        {#                            {{ olympiad.name }} (ID: {{ olympiad.id }})#}
        {#                            <form method="post" action="{% url 'main:delete_register' olympiad.id student.id %}"#}
        {#                                  style="display:inline;">#}
        {#                                {% csrf_token %}#}
        {#                                <button type="submit">Удалить</button>#}
        {#                            </form>#}
        {#                        </li>#}
        {#                    {% endfor %}#}
        {#        </ul>#}
        {#    </li>#}
        {#{% endfor %}#}
        {#</ul>#}


    </div>
</div>
</body>
</html>